name: GitHub Actions Demo
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3000935@ds.study.iitm.ac.in
        run: echo "Hello World!"
      
      - uses: actions/checkout@v3
      
      - name: List files
        run: ls -la

