Created README.md

name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 22f3000935@ds.study.iitm.ac.in
        run: echo "Hello, world! This step includes the required email address."